version: 1

name: s3-static-website

pipelines:
  dev:
    phases:
    - type: github
      name: GitHub
      owner: dsw88
      repo: s3-static-website
      branch: master
    - type: codebuild
      name: Build
      build_image: aws/codebuild/ruby:2.3.1
    - type: handel
      name: DevDeploy
      environments_to_deploy:
        - dev